FlugBuch/FlugBuch/Models/AirplaneSearchViewModel.cs
namespace FlugBuch.Models
{
    public class AirplaneSearchViewModel
    {
        public string AirplaineSearchString { get; set; }

        public FlightPointInfoViewModel  EndPointViewModel{ get; set; }

        public FlightPointInfoViewModel StartPointViewModel { get; set; }

    }
}

FlugBuch/FlugBuch/Models/AirplaneViewModel.cs
namespace FlugBuch.Models
{
    public class AirplaneViewModel
    {
        public string AirplaneName { get; set; }
    }
}

FlugBuch/FlugBuch/Models/AirplanesListViewModel.cs
using System.Collections.Generic;

namespace FlugBuch.Models
{
    public class AirplanesListViewModel
    {
        public IEnumerable<AirplaneViewModel> Airplanes { get; set; }
    }
}

FlugBuch/FlugBuch/Models/FlightPointInfoViewModel.cs
using System;

namespace FlugBuch.Models
{
    public class FlightPointInfoViewModel
    {
        public DateTime Date { get; set; }
        public int FlightPointId { get; set; }
    }
}

FlugBuch/FlugBuch/Controllers/AirplaneSearchController.cs
using FlugBuch.Adapters;
using FlugBuch.DomainModels;
using FlugBuch.Helpers.Context;
using FlugBuch.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace FlugBuch.Controllers
{
    public class AirplaneSearchController : Controller
    {
        private readonly AirplaneSearchAdapter _airplainSearchAdapter;
        private readonly ISearchProvider<Airplane> _searchProvider;

        public AirplaneSearchController(AirplaneSearchAdapter airplainSearchAdapter, ISearchProvider<Airplane> searchProvider)
        {
            _airplainSearchAdapter = airplainSearchAdapter;
            _searchProvider = searchProvider;
        }
                
        [HttpGet]
        public IActionResult Index()
        {
            var model = _airplainSearchAdapter.CreateAirplaineViewModel();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SearchAirplaneByString(string airplaineSearchString)
        {
            var airplanes = _searchProvider.SearchByContext(new AirplaneSearchContext (airplaineSearchString));
            if (airplanes.Any())
            {
                var airplanesListViewModel = _airplainSearchAdapter.CreateAirplainesListViewModel(airplanes);
                return View("AirplanesList", airplanesListViewModel);
            };

            var model = _airplainSearchAdapter.CreateAirplaineViewModel();
            return View("Index", model);
        }
    }
}

FlugBuch/FlugBuch/Views/AirplaneSearch/AirplanesList.cshtml
@model FlugBuch.Models.AirplanesListViewModel
@{
    ViewData["Title"] = "AirplanesList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>AirplanesList</h2>

@foreach (var airplane in Model.Airplanes)
{
    <div>@airplane.AirplaneName</div>
}

FlugBuch/FlugBuch/Views/AirplaneSearch/Index.cshtml
@using FlugBuch.Models
@model AirplaneSearchViewModel
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Search of Airplanes</h2>
    <form asp-controller="AirplaneSearch" asp-action="SearchAirplaneByString" asp-route-returnurl="@ViewBag.ReturnUrl" method="post" class="form-row form-group">
            <label asp-for="AirplaineSearchString" class="col-md-3 control-label"></label>
            <input asp-for="AirplaineSearchString" class="form-control" />
            <span asp-validation-for="AirplaineSearchString"class = " text-danger"></span>
            <button class="btn btn-default col-md-1" type="submit"><i class="fa fa-search"></i></button>
    </form>
    <form asp-controller="AirplaneSearch" asp-action="SearchAirplaneByStartEndPoints" asp-route-returnurl="@ViewBag.ReturnUrl" method="post" class="form-row  form-group">
        <div class="form-group col-md-6">
            <label asp-for="StartPointViewModel" class="col-md-3 control-label"></label>
            @Html.Partial("_FlightPointInfo", Model.StartPointViewModel)
            <span asp-validation-for="StartPointViewModel" class=" text-danger"></span>
        </div>
        <div class="form-group col-md-6">
            <label asp-for="EndPointViewModel" class="col-md-3 control-label"></label>
            @Html.Partial("_FlightPointInfo", Model.StartPointViewModel)
            <span asp-validation-for="EndPointViewModel" class=" text-danger"></span>
        </div>
            <button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
    </form>

FlugBuch/FlugBuch/Views/Shared/_FlightPointInfo.cshtml
@using FlugBuch.Models
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, FlugBuch.TagHelpers
@model FlightPointInfoViewModel
<div class="form-group">
    <label asp-for="Date" class="col-md-3 control-label"></label>
    <div class="col-md-9">
        <input asp-for="Date" type="text" data-provide="datepicker" class="form-control"/>
        <span asp-validation-for="Date" class=" text-danger"></span>
    </div>    
</div>
<div class="form-group">
    <label asp-for="FlightPointId" class="col-md-3 control-label"></label>
    <div class="col-md-9">
        <input asp-for="FlightPointId" type="text" class="form-control" />
        <span asp-validation-for="FlightPointId" class=" text-danger"></span>
    </div>
</div>
<script src="~/lib/bootstrap-datepicker/dist/js/bootstrap-datepicker.js"></script>
<link rel="stylesheet" href="~/lib/bootstrap-datepicker/dist/css/bootstrap-datepicker.css" />

FlugBuch/FlugBuch/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FlugBuch</title>
    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css">
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>

</head>
<body>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/popper.js/dist/umd/popper.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>

       <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - FlugBuch</p>
        </footer>
    </div>

    
        <script src="~/js/site.js" asp-append-version="true"></script>
    
    @RenderSection("Scripts", required: false)
</body>
</html>